### ISSUE TITLE
sayohat: [deferlar taxlanishi]

### ISSUE THREAD

**Issue by ulugbekrozimboyev** [faxriddin/go-tour-uz#11]
Mazmuni: /flowcontrol/13

Deferred function calls are pushed onto a stack. When a function returns, its deferred calls are executed in last-in-first-out order.

Defer qilingan amallar stack(navbat)ga yoziladi. Qachon funksiya ishini tugatsa, shunda defer qilingan amallar "oxirgi kirgan birinchi chiqadi" tartibi bõyicha bajariladi.

**Comment by faxriddin** [comment]
@ulugbekrozimboyev rahmat.
