### ISSUE TITLE
sayohat: [shaffof]

### ISSUE THREAD

**Issue by ulugbekrozimboyev** [faxriddin/go-tour-uz#13]
Mazmuni: /moretypes/4

Mantiqiy manzillarni fizik manzillarga ko'rsatkichlar orqali o'tkazish shaffof.

Mantiqiy manzillarni fizik manzillarga ko'rsatkichlar orqali o'tkazish bexato ishlaydi.

**Comment by faxriddin** [comment]
@ulugbekrozimboyev rahmat!
