### ISSUE TITLE
Terminlar

### ISSUE THREAD

**Issue by ulugbekrozimboyev** [faxriddin/go-tour-uz#14]
tuzilma - struktura
xarita - map
qirqim - slice

shu terminlarni o'zgartirmaslik taklifini bildiraman.

**Comment by faxriddin** [comment]
Ha shunday qilish kerak. Ajoyib taklif, Ushbu fikrni ko'pchilik taklif etdi. Avvaliga shunday qoldirish maqsadida ish boshlagandim. Keyiniga ommani qanday qabul qilishini ko'rish maqsadida ularni ham tarjima qilgandim. Bu og'ir mavzu shu tufayli...
U holda bundan keyingi uchragan(qo'llanmadagi) shu kabi so'zlarni yoki atamalarni internatsional so'z yoki dasturlash tilining o'z terminlari deya qabul qilamiz. O'ylaymizki ushbu xulosamiz foydalanuvchilar o'rganishi uchun tushunmovchilikka olib kelmaydi. 
@ulugbekrozimboyev rahmat!
