### ISSUE TITLE
sayohat: [Interfays]

### ISSUE THREAD

**Issue by ulugbekrozimboyev** [faxriddin/go-tour-uz#17]
Mazmuni: /methods/4

Interfeys turi bu metodlar to'plami bilan aniqlanishidir.

Menimcha unchalik manosi o'xshamagan. Iltimos qayta ko'rib chiqsangiz.
Masalan: Interfays - bu faqat metodlar (nomlari) to'plamidandir.

**Comment by faxriddin** [comment]
@ulugbekrozimboyev siz haqsiz. Interfeysning o'zi bir tur. Va bu tur metodlar to'plamini o'zida mujassamlashtirgan bo'ladi. Shu sababli "Interfeys bu - metodlar to'plamini aniqlash uchun xizmat qiluvchi tur." desak yanada tushunarliroq bo'larkan. Rahmat!
