### ISSUE TITLE
sayohat: [Run qilganda xato]

### ISSUE THREAD

**Issue by Zikoi5** [faxriddin/go-tour-uz#21]
Ozbekcha go tour run qilganda xato beryapti

**Comment by Zikoi5** [comment]
![image](https://user-images.githubusercontent.com/12369295/85431823-81c5be80-b59b-11ea-89fe-46158b7aed90.png)

**Comment by Zikoi5** [comment]
Diskriminatsiya bu? Boshqa tillada ishlidi, o'zbechaga keganda ishlamidimi?

**Comment by faxriddin** [comment]
Servicelar google consoleda ochilgandi. Google consolega to'lov amalga oshirilmaganligi uchun o'chib qolgan. Uzr. Imkon bo'lganda yana ishga tushirib qo'yishga harakat qilamiz.

**Comment by faxriddin** [comment]
yana ishga tushirib qo'yildi, ishlatib ko'rsangiz bo'ladi.
