### ISSUE TITLE
Re-deployment needed after appspot Go1.9 depreprecation

### ISSUE THREAD

**Issue by ALTree** [faxriddin/go-tour-uz#22]
Hi there,

this Go tour translation is currently offline due to the appspot
deprecation of Go1.9:

```
Go 1.9 is no longer available.
Please refer to https://goo.gl/aESk5L for more information.
```

As documented in the linked page:

> To continue running your apps, migrate them to the Go 1.11 standard
  runtime or newer runtimes.

A re-deployment is needed to bring the translation back online.

**Comment by faxriddin** [comment]
upgrade successful
