### ISSUE TITLE
Main title

### ISSUE THREAD

**Issue by ulugbekrozimboyev** [faxriddin/go-tour-uz#3]
"Go bo'yicha sayohat" ni "Go bo'ylab sayohat"  deyishni taklif qilaman

**Comment by faxriddin** [comment]
@ulugbekrozimboyev,  Go bo'ylab uni yoqasida degan ma'noni anglatib qolmaydimikan?
Huddi daryo bo'ylab deganiday.

**Comment by faxriddin** [comment]
@ulugbekrozimboyev "Go ga sayohat" deb nomlasak qanday bo'larkan!

**Comment by faxriddin** [comment]
Yaxshi "Go ga sayohat" deya qolamiz unda.
