### ISSUE TITLE
nolta argument

### ISSUE THREAD

**Issue by ulugbekrozimboyev** [faxriddin/go-tour-uz#4]
Mazmuni: /basics/4
Funksiyalar nolta yoki ko'p argument qabul qilishi mumkin. 

Funksiya argument qabul qilmasligi yoki birnechta argument qabul qilishi mumkin.

**Comment by faxriddin** [comment]
Matn "Funksiya bir nechta argument qabul qilishi yoki umuman qabul qilmasligi ham mumkin." ga o'zgartirildi. 
@ulugbekrozimboyev Rahmat!
