### ISSUE TITLE
sayohat: [õynab kõrish]

### ISSUE THREAD

**Issue by ulugbekrozimboyev** [faxriddin/go-tour-uz#8]
Mazmuni: /flowcontrol/8

Funksiyalar va takrorlanishlarni o'ynab ko'rishning eng sodda yo'li bu Nyuton usuli yordamida kvadrat ildizni qo'llashdir.

Funksiyalar va takrorlanishlarni amalda sinab ko'rishning eng sodda yo'li bu Nyuton usuli yordamida kvadrat ildizni qo'llashdir.

**Comment by faxriddin** [comment]
Funksiyalar va takrorlanishlarni amalda sinab ko'rishning eng sodda yo'li bu Nyuton usuli yordamida kvadrat ildizni hisoblashdir. @ulugbekrozimboyev  Rahmat!
